### ISSUE TITLE
Send final description to a persistent notification on HA

### ISSUE THREAD

**Issue by NightHawkATL** [remimikalsen/ollama_vision#6]
Since I am not running Frigate, I can't _follow_ the example on sending a notification and I am not much for the yaml (or jinja) config of automations. Is there an easy way to add the final output to a UI automation setup where once the description is ready, it will send to a persistent notification? 

![Image](https://github.com/user-attachments/assets/513bafd0-c801-46ae-97f0-48f1e3e5b32a)

**Comment by remimikalsen** [comment]
Sorry for the late reply. Just use the ollama_vision_image_analyzed event, and look for the image_name you're looking for. Just remember that in this context the "image_name" is a setting in Ollama Vision, not the actual name of the image you're sending. Here is an example without Frigate:

```
alias: Ollama Vision - Send beskrivelse til telefon
description: Catches ollama_vision_image_analyzed event and sends final_description.
triggers:
  - trigger: event
    event_type: ollama_vision_image_analyzed
    event_data:
      image_name: front_door
conditions: []
actions:
  - action: notify.mobile_app_mymobile
    continue_on_error: true
    data:
      message: Picture of a person outside
      data:
        ttl: 0
        priority: high
        sticky: true
        image: |
          {{ trigger.event.data.image_url }}
  - action: notify.mobile_app_mymobile
    continue_on_error: true
    data:
      title: Description of a person outside
      message: |
        {{ trigger.event.data.final_description }}
      data:
        ttl: 0
        priority: high
        sticky: true

```

I can't test it right now, but I think maybe local images may not be visible out of the box when sent to the HA Companion App.
